[project]
name = "modelsmith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "questionary>=2.1.0",
    "rich>=14.0.0",
    "scikit-learn>=1.7.0",
]
